Repository Hanbang-NeungYo-Baeksook/Schedule-Hanaro-Front, pull requests merged in 2024-10, with the labels that each got.

#24 [Design] 🍀지도 UI 구현
  src/assets/icons/ic_home.svg
  src/assets/icons/ic_outline-account-circle.svg
  src/assets/icons/ic_outline-calendar-today.svg
  src/assets/icons/ic_round-map.svg
  src/assets/icons/nav_calendar.svg
  src/assets/icons/nav_home.svg
  src/assets/icons/nav_map.svg
  src/assets/icons/nav_mypage.svg
  src/assets/icons/nav_reservationList.svg
  src/assets/icons/streamline_task-list.svg
  src/assets/icons/tabler_home.svg
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Layout/MapLayout/index.tsx
  src/components/Map/BranchCard.tsx
  src/components/Map/index.tsx
  src/components/Nav/Nav.const.ts
  src/components/Nav/Nav.module.css
  src/components/Nav/Nav.tsx
  src/components/chips/Chips.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/components/ui/drawer.tsx
  src/components/ui/searchInput.tsx
  src/constants/Map.ts
  src/index.css
  src/main.tsx
  src/pages/Main/index.tsx
  tailwind.config.js
  tsconfig.app.tsbuildinfo
Labels: Design

#33 [Feat] 🍀실제 MOCK 데이터로 변환 후 마커 설정
  package.json
  pnpm-lock.yaml
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Direction/BottomFloatingBox/BranchInfo.tsx
  src/components/Direction/BottomFloatingSheet.tsx
  src/components/Direction/bankInfo.tsx
  src/components/Direction/index.tsx
  src/components/Layout/MapLayout/index.tsx
  src/components/Map/BranchCard.tsx
  src/components/Map/index.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/components/ui/searchInput.tsx
  src/constants/Map.ts
  src/hooks/useRouter.tsx
  src/index.css
  src/mock/branch_mock.ts
  src/pages/Map/index.tsx
  src/types/branch.ts
  tailwind.config.js
  tsconfig.app.tsbuildinfo
Labels: Design, Feat, Fix

#34 [Feat] 🍎 목데이터 변경 및 마커 이미지 추가
  .gitignore
  pnpm-lock.yaml
  src/assets/icons/marker-atm-selected.svg
  src/assets/icons/marker-atm.svg
  src/assets/icons/marker-bank-reserved-selected.svg
  src/assets/icons/marker-bank-reserved.svg
  src/assets/icons/marker-bank-selected.svg
  src/assets/icons/marker-bank.svg
  src/assets/icons/marker-branch.svg
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Direction/BottomFloatingBox/BranchInfo.tsx
  src/components/Direction/BottomFloatingBox/ReservationButton.tsx
  src/components/Direction/Modal/index.tsx
  src/components/Direction/TopSheet/DepartureArrivalAddress.tsx
  src/components/Direction/TopSheet/index.tsx
  src/components/Direction/index.tsx
  src/components/Layout/MainLayout/index.tsx
  src/components/Map/BranchCard.tsx
  src/components/Map/Marker.tsx
  src/components/Map/index.tsx
  src/components/Register/ConsultationSelect.tsx
  src/components/ui/button.tsx
  src/hooks/useMap.ts
  src/hooks/useRouter.tsx
  src/index.css
  src/mock/branch_mock.ts
  src/pages/Main/MyCard.tsx
  src/pages/Main/index.tsx
  src/pages/Register/Visit/index.tsx
  src/pages/Reservation/Visit/index.tsx
  src/types/branch.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: Design, Feat

#36 [Feat] 🌱 관리자 페이지 구현
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Admin/AnswerInput.tsx
  src/components/Admin/Customer.tsx
  src/components/Admin/Header.tsx
  src/components/Admin/Infocard.tsx
  src/components/Admin/Inquiry/FilterAndSearch.tsx
  src/components/Admin/Inquiry/InquiryList.tsx
  src/components/Admin/Inquiry/ReplyState.tsx
  src/components/Admin/Next.tsx
  src/components/Admin/Sidebar.tsx
  src/components/Admin/WaitingNum.tsx
  src/components/Layout/AdminLayout/index.tsx
  src/components/Map/BranchCard.tsx
  src/constants/customer.ts
  src/hooks/useRouter.tsx
  src/index.css
  src/main.tsx
  src/pages/Admin/Call/index.tsx
  src/pages/Admin/Inquiry/Answer/Detail/index.tsx
  src/pages/Admin/Inquiry/Answer/Input/index.tsx
  src/pages/Admin/Inquiry/index.tsx
  src/pages/Admin/Main/index.tsx
  src/pages/Admin/Visit/index.tsx
  src/pages/Admin/index.ts
  src/pages/BranchDetail/index.tsx
  src/types/inquiry.ts
Labels: Feat

#40 [Design] 🍀map 페이지에서 Bottom Floating Box 디자인 수정
  pnpm-lock.yaml
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Direction/BottomFloatingBox/BranchInfo.tsx
  src/components/Direction/BottomFloatingBox/index.tsx
  src/components/Direction/BottomFloatingSheet.tsx
  src/components/Direction/TopSheet/index.tsx
  src/components/Direction/bankInfo.tsx
  src/components/Direction/index.tsx
  src/components/Layout/MapLayout/index.tsx
  src/components/Map/MapChips.tsx
  src/components/Map/index.tsx
  src/components/ui/branch/direction.tsx
  src/components/ui/direction.tsx
  src/hooks/useMap.ts
  src/pages/BranchDetail/index.tsx
  src/pages/Direction/index.tsx
  src/pages/ReservationDetail/Visit/index.tsx
Labels: Design, Feat

#43 [Feat] 🍀admin / client layout 분리
  src/assets/icons/navigate.svg
  src/components/Admin/Customer.tsx
  src/components/Admin/Inquiry/FilterAndSearch.tsx
  src/components/Direction/BottomFloatingBox/BranchInfo.tsx
  src/components/Direction/BottomFloatingBox/ReservationButton.tsx
  src/components/Direction/BottomFloatingBox/index.tsx
  src/components/Header/ReservationHeader.tsx
  src/components/Layout/AdminLayout/index.tsx
  src/components/Layout/ClientLayout/index.tsx
  src/components/Layout/ReservationLayout/index.tsx
  src/components/Nav/Nav.const.ts
  src/components/Register/DateAndTimePicker.tsx
  src/components/Tabs/Tabs.tsx
  src/components/ui/direction.tsx
  src/constants/admin.ts
  src/constants/customer.ts
  src/constants/index.ts
  src/constants/maxCapacity.ts
  src/constants/reservation.ts
  src/hooks/useRouter.tsx
  src/index.css
  src/pages/Main/index.tsx
  src/pages/Register/Visit/index.tsx
  src/pages/Reservation/index.tsx
Labels: Design, Feat

#45 [Design] 🍀마이페이지 UI 구현
  src/assets/icons/branch/direction.svg
  src/assets/icons/nav_calendar.svg
  src/assets/icons/nav_map.svg
  src/assets/icons/nav_mypage.svg
  src/assets/icons/nav_reservationList.svg
  src/components/Layout/MypageLayout/index.tsx
  src/components/Nav/Nav.tsx
  src/components/ui/direction.tsx
  src/hooks/useRouter.tsx
  src/pages/Mypage/index.tsx
  src/pages/Reservation/index.tsx
  src/pages/ReservationDetail/Visit/index.tsx
Labels: Design

#50 [Feat] 🍀길찾기 toast 적용
  src/assets/icons/hyperlink.svg
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Direction/BottomFloatingBox/BranchInfo.tsx
  src/components/Direction/BottomFloatingBox/index.tsx
  src/components/Direction/index.tsx
  src/components/Map/BranchCard.tsx
  src/components/Nav/Nav.const.ts
  src/components/ui/direction.tsx
  src/constants/mypage.ts
  src/hooks/useRouter.tsx
  src/mock/branch_mock.ts
  src/pages/BranchDetail/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/Register/Call/index.tsx
  src/pages/ReservationDetail/Visit/index.tsx
Labels: Design, Feat, Fix
