Repository Hanbang-NeungYo-Baeksook/Schedule-Hanaro-Front, pull requests merged in 2024-12, with the labels that each got.

#72 [Feat] 🍎 길찾기 버그 수정 및 메인 페이지 디자인 변경
  custom.d.ts
  package.json
  pnpm-lock.yaml
  src/assets/icons/StarGgonge.svg
  src/assets/icons/automobile.svg
  src/assets/icons/call_reservation.svg
  src/assets/icons/inquiry_reservation.svg
  src/assets/icons/pedestrain.svg
  src/assets/images/map.png
  src/assets/images/map.svg
  src/assets/images/md-map.svg
  src/components/Direction/BottomFloatingBox/BranchInfo.tsx
  src/components/Direction/BottomFloatingBox/ChangeToggle.tsx
  src/components/Direction/BottomFloatingBox/index.tsx
  src/components/Direction/TopSheet/DepartureArrivalTime.tsx
  src/components/Direction/TopSheet/TotalDistance.tsx
  src/components/Direction/TopSheet/TotalTime.tsx
  src/components/Direction/index.tsx
  src/components/Layout/MapTestLayout/index.tsx
  src/components/Map/MyLocation.tsx
  src/components/Map/index.tsx
  src/components/ui/badge.tsx
  src/hooks/map-context.tsx
  src/hooks/timer-hooks.ts
  src/hooks/useRouter.tsx
  src/pages/BranchDetail/index.tsx
  src/pages/Main/MyCard.tsx
  src/pages/Main/RecommendCard.tsx
  src/pages/Main/index.tsx
  src/pages/MapTest/index.tsx
  src/pages/ReservationDetail/Visit/index.tsx
Labels: Design, Feat, Fix

#75 [Feat] 🍀추천 영업점 목록 UI
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  Dockerfile
  package.json
  pnpm-lock.yaml
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Map/RecBranch.tsx
  src/components/Map/RecBranchBox.tsx
  src/components/ui/index.tsx
  src/mock/branch_mock.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/types/branch.ts
Labels: Design, Feat

#96 [Fix] 🍎 React 404 Not Found 버그 조치
  .htaccess
Labels: Fix

#147 [Design] 🍎 모든 페이지 반응형 디자인 적용 완료
  src/api/Api.tsx
  src/assets/icons/marker-current.png
  src/assets/images/map.png
  src/components/Admin/WaitingNum.tsx
  src/components/Header/ReservationHeader.tsx
  src/components/Nav/Nav.tsx
  src/components/Reservation/CallList.tsx
  src/components/Reservation/ChangeToggle.tsx
  src/components/Reservation/InquiryList.tsx
  src/components/ui/index.tsx
  src/constants/index.ts
  src/constants/inquiryCategory.ts
  src/pages/Chat/index.tsx
  src/pages/Main/index.tsx
  src/pages/Reservation/Call/index.tsx
  src/pages/Reservation/Inquiry/index.tsx
  src/pages/Reservation/Visit/index.tsx
Labels: Design, Fix

#148 [Fix] 🍎 전화 예약 상세 페이지 반응형 디자인 오류 수정
  src/pages/ReservationDetail/Call/index copy.tsx
  src/pages/ReservationDetail/Call/index.tsx
Labels: Design, Fix

#171 [Refactor] 🍎 불필요한 Rerendering 제거 및 디자인 수정
  .github/workflows/cicd.yml
  .github/workflows/ssl.yml
  Dockerfile
  entrypoint-http.sh
  entrypoint-https.sh
  nginx-http.conf
  nginx-https.conf
  src/api/Api.ts
  src/api/admin/auth.ts
  src/api/auth.ts
  src/api/customer/auth.ts
  src/api/customer/calls.ts
  src/assets/icons/marker-current.png
  src/components/Map/BranchCard.tsx
  src/components/Map/Marker.tsx
  src/constants/route.ts
  src/hooks/query/admin/usePostAdminLoginQuery.ts
  src/hooks/query/customer/useGetCallListQuery.ts
  src/hooks/query/customer/usePostLogin.ts
  src/hooks/useRouter.tsx
  src/pages/Chat/index.tsx
  src/pages/Signin/index.tsx
Labels: Design, Fix, Refactor

#176 [Feat] 🍎 사용자 Client API 구현 완료
  src/api/customer/branches.ts
  src/api/customer/calls.ts
  src/api/customer/customers.ts
  src/api/customer/inquires.ts
  src/components/Admin/main/CallTimeSelector.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Header/ReservationHeader.tsx
  src/components/Layout/ReservationLayout/index.tsx
  src/components/Map/RecBranch.tsx
  src/components/Map/index.tsx
  src/components/Register/DateAndTimePicker.tsx
  src/components/Reservation/CallList.tsx
  src/components/Reservation/InquiryList.tsx
  src/constants/queryKeys.ts
  src/hooks/query/customer/useGetBranchList.ts
  src/hooks/query/customer/useGetBranchRecommendList.ts
  src/hooks/query/customer/useGetCallAvailability.ts
  src/hooks/query/customer/useGetCallList.ts
  src/hooks/query/customer/useGetCustomerDetail.ts
  src/hooks/query/customer/useGetInquiryList.ts
  src/pages/BranchDetail/index.tsx
  src/pages/Chat/index.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/Register/Call/index.tsx
  src/pages/Register/Inquiry/index.tsx
  src/pages/Register/Visit/index.tsx
  src/pages/Reservation/Inquiry/index.tsx
  src/pages/ReservationDetail/Call/index.tsx
  src/pages/ReservationDetail/InquiryDetail/index.tsx
  src/pages/ReservationDetail/ReservationDetailInquiryTags/index.tsx
  src/stores/atom.ts
  src/utils/timeUtil.ts
Labels: Feat, Fix

#177 [Feat] 🍀call & inquiry 페이지네이션 추가
  src/api/Api.ts
  src/api/Error.ts
  src/api/admin/auth.ts
  src/api/admin/calls.ts
  src/components/Admin/Call/ListOfCallInquiry.tsx
  src/components/Admin/Call/SearchConditionSetting.tsx
  src/components/Admin/Inquiry/DetailCustomerInfo.tsx
  src/components/Admin/Inquiry/InputCustomerInfo.tsx
  src/components/Admin/Inquiry/InquiryList.tsx
  src/components/Admin/Inquiry/ReplyState.tsx
  src/components/Admin/ListPagination.tsx
  src/components/Admin/customer/CustomerContainer.tsx
  src/components/Admin/customer/CustomerInquiryList.tsx
  src/components/Admin/main/CallContainer.tsx
  src/components/Admin/main/CallTimeSelector.tsx
  src/components/Admin/main/InquiryContainer.tsx
  src/components/Admin/main/WaitingBox.tsx
  src/components/ui/pagination.tsx
  src/hooks/query/admin/useGetCallList.ts
  src/hooks/query/admin/useGetCallWaitList.ts
  src/mock/adminInquiry.ts
  src/pages/Admin/online/Call/Detail/index.tsx
  src/pages/Admin/online/Call/index.tsx
  src/pages/Admin/online/Inquiry/Answer/Detail/index.tsx
  src/pages/Admin/online/Inquiry/Answer/Input/index.tsx
  src/pages/Admin/online/Inquiry/index.tsx
  src/types/customer.ts
  src/types/enum.ts
  src/types/global.d.ts
  src/types/inquiry.ts
Labels: Feat, Fix
